### ISSUE TITLE
[bugfix] 실서버 테이블 생성 시 dml encoding 문제

### ISSUE THREAD

**Issue by myrhymetree** [goalapa/spring-cacamuca#84]
🗺️Location
원격 서버(배포한 서버)

✏️Description
데이터베이스에 초기 설정한 dml에서 한글깨짐 현상 발생
-> 로컬서버에서는 DBMS 기본 설정이 UTF-8로 되어있으나, 원격 서버에서는 다른 encoding방식을 기본값으로 사용하는것으로 추정됨.

✅TODO
-
- [x] application 초기설정으로 dml encoding UTF-8로 설정

🐾ETC
-

**Comment by myrhymetree** [comment]
다음과 같이 변경하면 해결되는것으로 확인했습니다.

  sql:
    init:
      data-locations: classpath:db/data/data.sql
      mode: always
      platform: mysql
      encoding: UTF-8

**Comment by myrhymetree** [comment]
@numerical43 @Dylan-SonJungin @bbbbooo @juunewon 다음과 같이 develop브랜치에 적용했습니다.

**Comment by numerical43** [comment]
확인했습니다!
